### ISSUE TITLE
release in docs should reflect actual release

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/py-xmlasdict#5]
When checking the https://xmlasdict.readthedocs.io/ I see the docs still consider the release as v0.0.0
this is due to the fact that `docs/conf.py` is not reading the `xmlasdict/__version__.py`

We should find an elegant solution to avoid this

- either by linking the actual versions in both files. Most likely by having docs/conf.py to import/include/use/execute (like setup.py does) the `__version__.py`
- either by abusing the `make release` to actually update or at least break on mismatch

**Comment by RoryMMMM** [comment]
I can't find a reference to any version on https://xmlasdict.readthedocs.io/ ? I see that the docs show the version as "latest" but v0.0.0 isn't showing up for me anywhere

**Comment by marc-portier** [comment]
ah, I snatched the PDF --> https://xmlasdict.readthedocs.io/_/downloads/en/latest/pdf/

and actually: the fact that up to now all docs have been pushed out as v.0.0.0 I assume we have been overwriting that version, so it stays "the latest" and no previous versions can be browsed ?

wdyt?

**Comment by RoryMMMM** [comment]
Okay, you can set which versions of docs are visible. By default it's 
"latest" = most recent push to git repo 
"stable" = most recent release
You can select other versions in the readthedocs project settings. I've set up v0.2.1 to be one of those. 

Unfortunately I can't figure out what's going on with the version number in the pdf's... I've changed the docs/conf.py version to read from the __version__.py file but it still shows v0.0.0...

**Comment by marc-portier** [comment]
@RoryMMMM , 
something tels me we had this solved?
please confirm & close?
